export enum UnitType {
  KG = "KG",
  LITER = "LITER",
  METER = "METER",
  PIECE = "PIECE",
  BOX = "BOX",
  BOTTLE = "BOTTLE",
  CAN = "CAN",
  PACK = "PACK",
  SET = "SET",
  ROLL = "ROLL",
  TUBE = "TUBE",
  BAG = "BAG",
  JAR = "JAR",
  SACHET = "SACHET",
  DOZEN = "DOZEN",
  BUNDLE = "BUNDLE",
  TRAY = "TRAY",
  CASE = "CASE",
  PALLET = "PALLET",
  CONTAINER = "CONTAINER",
  UNIT = "UNIT",
  OTHER = "OTHER",
  MOL = "MOL",
  G = "G",
  
}
